build:
  environment:
    php:
      version: '8.0'
  tests:
    override:
      - command: vendor/bin/phpunit -c phpunit.coverage.xml.dist
        coverage:
          file: var/coverage/coverage.xml
          format: clover

checks:
  php: true

filter:
  excluded_paths:
    - tests/*
